# basic options
title: Data Science Portfolio
author: Santosh Omprakash
email: oneorss@gmail.com
description: A wonderful site
github_username:  santosh0924

# Build settings
markdown: kramdown
theme: minima
